@echo off
REM ╔══════════════════════════════════════════════════════════════════╗
REM ║         WSL Config — 8 GB Laptop Profile (Dynabook L50 et al.)   ║
REM ║                                                                  ║
REM ║  Writes %USERPROFILE%\.wslconfig with values that leave 3 GB     ║
REM ║  for Windows itself and give 5 GB to the WSL VM that runs        ║
REM ║  Docker. WSL only consumes RAM it actually uses, but this cap    ║
REM ║  STOPS Docker from eating all 8 GB and freezing the laptop.      ║
REM ║                                                                  ║
REM ║  Run: double-click. Then RESTART Docker Desktop.                 ║
REM ╚══════════════════════════════════════════════════════════════════╝

setlocal

set "WSLCFG=%USERPROFILE%\.wslconfig"

echo.
echo  Writing tuned WSL config to: %WSLCFG%
echo.

> "%WSLCFG%" (
    echo # Generated by WSLCONFIG-8GB.bat for Krexion low-RAM mode
    echo [wsl2]
    echo memory=5GB
    echo processors=4
    echo swap=4GB
    echo localhostForwarding=true
    echo.
    echo [experimental]
    echo autoMemoryReclaim=gradual
    echo sparseVhd=true
)

echo  Done. Now restart Docker Desktop so it picks up the new limit:
echo     1. Right-click Docker tray icon → Quit Docker Desktop
echo     2. Start Docker Desktop again
echo     3. Wait for the whale icon to stop animating
echo     4. Re-run INSTALL-KREXION.bat
echo.
echo  Or run from PowerShell:  wsl --shutdown
echo.
pause
endlocal
