"""
Krexion — App Releases & Auto-Update Module
============================================
Admin publishes releases at https://krexion.com → customer's local install
polls for updates → shows a "New version available" banner → one-click apply.

Endpoints:
  Admin (cloud, JWT-required):
    POST   /api/admin/releases                — create a release
    GET    /api/admin/releases                — list all releases
    PATCH  /api/admin/releases/{id}           — edit notes / severity
    DELETE /api/admin/releases/{id}           — remove a release

  Customer (license-auth):
    GET    /api/system/latest-version         — newest published release
    GET    /api/system/version                — current local version (no-auth)

  Customer (local-only, JWT-required):
    POST   /api/system/install-update         — write flag file so the host
                                                updater script picks it up

A `VERSION` file at /app/backend/VERSION holds the running version on each
install (cloud OR local). Updater compares semver strings.
"""

from __future__ import annotations

import json
import logging
import os
import re
import subprocess
import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Optional

from fastapi import APIRouter, Depends, Header, HTTPException, Request

logger = logging.getLogger(__name__)
releases_router = APIRouter(tags=["releases"])

# Bound from server.py
_db: Any = None
_get_current_admin: Any = None
_get_current_user: Any = None

VERSION_FILE = Path(__file__).parent / "VERSION"
UPDATE_FLAG_FILE = Path("/data/update_requested.flag")
SEMVER_RE = re.compile(r"^(\d+)\.(\d+)\.(\d+)(?:[.-].+)?$")


def _bind(*, main_db, get_current_admin, get_current_user) -> None:
    global _db, _get_current_admin, _get_current_user
    _db = main_db
    _get_current_admin = get_current_admin
    _get_current_user = get_current_user


def _now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def current_version() -> str:
    try:
        if VERSION_FILE.exists():
            return VERSION_FILE.read_text(encoding="utf-8").strip() or "0.0.0"
    except Exception:  # noqa: BLE001
        pass
    return "0.0.0"


def _parse(v: str) -> tuple:
    m = SEMVER_RE.match((v or "").strip())
    if not m:
        return (0, 0, 0)
    return (int(m.group(1)), int(m.group(2)), int(m.group(3)))


def is_newer(remote: str, local: str) -> bool:
    return _parse(remote) > _parse(local)


def _bump_patch(version: str) -> str:
    """Bump the patch component of a semver version (1.0.4 → 1.0.5)."""
    major, minor, patch = _parse(version)
    if (major, minor, patch) == (0, 0, 0):
        return "1.0.0"
    return f"{major}.{minor}.{patch + 1}"


# Commit subjects we never want to surface in release notes — these are
# generated by the platform's auto-snapshot feature, not real changes the
# admin made.
_AUTO_COMMIT_PATTERNS = (
    "auto-commit for",
    "auto-generated changes",
)


def _collect_commits_since(since_iso: Optional[str], limit: int = 100) -> list[dict]:
    """Return a list of commits on the current branch made after `since_iso`.

    If `since_iso` is None, returns the most recent `limit` commits.
    Auto-generated platform commits keep their subjects (they ARE the
    real change checkpoints) but they're flagged so the caller can fall
    back to a file-based summary instead of bulleting the raw subjects.
    Returns [] silently if git is unavailable.
    """
    repo_root = Path(__file__).resolve().parent.parent  # /app
    if not (repo_root / ".git").exists():
        return []

    cmd = ["git", "-C", str(repo_root), "log",
           "--pretty=format:%H|%h|%s|%an|%ad", "--date=iso", "HEAD"]
    if since_iso:
        cmd.insert(4, f"--since={since_iso}")
    else:
        cmd.insert(4, f"-{int(limit)}")

    try:
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=15)
    except Exception as e:  # noqa: BLE001
        logger.warning(f"[releases] git log failed: {e}")
        return []

    commits = []
    for line in (result.stdout or "").splitlines():
        parts = line.split("|", 4)
        if len(parts) < 3:
            continue
        subject = parts[2].strip()
        if not subject:
            continue
        subj_lc = subject.lower()
        is_auto = any(p in subj_lc for p in _AUTO_COMMIT_PATTERNS)
        commits.append({
            "full_hash": parts[0],
            "hash": parts[1],
            "subject": subject,
            "author": parts[3] if len(parts) > 3 else "",
            "date": parts[4] if len(parts) > 4 else "",
            "is_auto": is_auto,
        })
        if len(commits) >= limit:
            break
    return commits


def _collect_changed_files_since(since_iso: Optional[str]) -> list[str]:
    """Return a deduplicated list of repo-relative file paths that changed
    in commits made after `since_iso` (or all of recent history if None).
    """
    repo_root = Path(__file__).resolve().parent.parent
    if not (repo_root / ".git").exists():
        return []

    cmd = ["git", "-C", str(repo_root), "log", "--name-only", "--pretty=format:", "HEAD"]
    if since_iso:
        cmd.insert(4, f"--since={since_iso}")
    else:
        cmd.insert(4, "-50")

    try:
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=20)
    except Exception as e:  # noqa: BLE001
        logger.warning(f"[releases] git log --name-only failed: {e}")
        return []

    files = set()
    for line in (result.stdout or "").splitlines():
        line = line.strip()
        if line:
            files.add(line)
    return sorted(files)


def _summarize_file_changes(files: list[str]) -> tuple[list[str], dict]:
    """Group changed files into human-readable categories and return
    (bullet_lines, raw_groups). Used when commit subjects are too noisy
    to use directly.
    """
    groups = {
        "Pages": [],
        "UI Components": [],
        "Backend modules": [],
        "Backend (server)": [],
        "Styles & theme": [],
        "Config & deployment": [],
        "Docs & guides": [],
        "Other": [],
    }
    for f in files:
        fl = f.lower()
        if f.startswith("frontend/src/pages/"):
            groups["Pages"].append(Path(f).stem)
        elif f.startswith("frontend/src/components/"):
            groups["UI Components"].append(Path(f).stem)
        elif f.startswith("frontend/src/") and (fl.endswith(".css") or "theme" in fl):
            groups["Styles & theme"].append(Path(f).name)
        elif f.startswith("backend/server.py"):
            groups["Backend (server)"].append("server.py")
        elif f.startswith("backend/") and f.endswith(".py"):
            groups["Backend modules"].append(Path(f).stem)
        elif fl.endswith((".md", ".txt")):
            groups["Docs & guides"].append(Path(f).name)
        elif fl.endswith((".yml", ".yaml", ".json", ".conf", "dockerfile", ".env.example", ".bat", ".ps1", ".sh")):
            groups["Config & deployment"].append(Path(f).name)
        else:
            groups["Other"].append(f)

    bullets: list[str] = []
    for label, items in groups.items():
        if not items:
            continue
        # Deduplicate and cap
        uniq = sorted(set(items))
        shown = uniq[:8]
        more = len(uniq) - len(shown)
        line = f"- {label} updated: " + ", ".join(shown)
        if more > 0:
            line += f" (+{more} more)"
        bullets.append(line)
    return bullets, groups


# ─── License → user resolver (shared with sync module) ────────────────
async def _validate_license(license_key: Optional[str]):
    if not license_key:
        raise HTTPException(status_code=401, detail="Missing X-Krexion-License header")
    lic = await _db.licenses.find_one({"license_key": license_key.strip()}, {"_id": 0})
    if not lic:
        raise HTTPException(status_code=401, detail="Invalid license key")
    if lic.get("status") and lic["status"] not in ("active", "issued"):
        raise HTTPException(status_code=403, detail=f"License is {lic['status']}")
    return lic


# ─── Admin endpoints ──────────────────────────────────────────────────
@releases_router.post("/api/admin/releases")
async def create_release(body: dict, admin: dict = Depends(lambda: None)):
    # Lazy admin check
    if _get_current_admin is None:
        raise HTTPException(503, "Admin auth not configured")
    # Actually we'll re-implement clean — use real admin dep
    raise HTTPException(500, "wired below")


# We need real admin dependency injection - we'll register handlers
# dynamically after _bind() is called from server.py. To keep it simple,
# define handlers that accept `admin` via the late-bound dependency.

def _build_admin_endpoints(get_admin_dep):
    """Register the actual admin endpoints with the correct admin dep."""
    router = APIRouter(tags=["releases-admin"])

    @router.post("/api/admin/releases")
    async def create(body: dict, admin: dict = Depends(get_admin_dep)):
        ver = (body.get("version") or "").strip()
        if not SEMVER_RE.match(ver):
            raise HTTPException(400, "version must be semver like 1.2.3")
        existing = await _db.app_releases.find_one({"version": ver})
        if existing:
            raise HTTPException(409, f"Version {ver} already exists")
        doc = {
            "id": str(uuid.uuid4()),
            "version": ver,
            "title": body.get("title", f"Krexion {ver}"),
            "notes": body.get("notes", ""),
            "severity": body.get("severity", "recommended"),  # info|recommended|critical
            "download_url": body.get("download_url", ""),
            "min_required_version": body.get("min_required_version", ""),
            "published": bool(body.get("published", True)),
            "created_at": _now_iso(),
            "created_by": admin.get("email") or admin.get("id"),
        }
        await _db.app_releases.insert_one(doc)
        doc.pop("_id", None)
        return doc

    @router.get("/api/admin/releases")
    async def list_releases(admin: dict = Depends(get_admin_dep)):
        items = await _db.app_releases.find({}, {"_id": 0}).sort("created_at", -1).to_list(200)
        return {"releases": items, "current_version": current_version()}

    @router.get("/api/admin/releases/auto-detect")
    async def auto_detect(admin: dict = Depends(get_admin_dep)):
        """Detect whether a new release should be published.

        Returns a suggested next version + draft release notes built from
        git activity since the last published release.  The admin can
        review and click "Publish release" — nothing is created here.

        Notes are built from real commit subjects when available; if the
        history is dominated by platform auto-checkpoints (no meaningful
        subjects) we fall back to a smart summary of changed files
        grouped by area (Pages, Components, Backend modules, etc.).
        """
        last_rel = await _db.app_releases.find_one(
            {"published": True}, sort=[("created_at", -1)], projection={"_id": 0}
        )
        since_iso = last_rel["created_at"] if last_rel else None
        commits = _collect_commits_since(since_iso, limit=100)
        files_changed = _collect_changed_files_since(since_iso)

        base_ver = (last_rel["version"] if last_rel else current_version()) or "0.0.0"
        suggested_version = _bump_patch(base_ver)

        # Ensure suggested version doesn't collide with an existing one
        # (e.g. unpublished draft). If it does, keep bumping.
        existing = await _db.app_releases.find({}, {"_id": 0, "version": 1}).to_list(500)
        existing_versions = {r.get("version") for r in existing}
        while suggested_version in existing_versions:
            suggested_version = _bump_patch(suggested_version)

        meaningful_commits = [c for c in commits if not c.get("is_auto")]
        notes_source = "none"
        notes = ""
        if meaningful_commits:
            notes = "\n".join(f"- {c['subject']}" for c in meaningful_commits)
            notes_source = "commits"
        elif files_changed:
            bullets, _grp = _summarize_file_changes(files_changed)
            if bullets:
                notes = "\n".join(bullets)
                notes_source = "files"

        # A release is "needed" if there is any change at all since the
        # last published version — either real commits or file changes.
        needs_release = bool(commits) or bool(files_changed)

        if needs_release:
            change_count = len(meaningful_commits) if meaningful_commits else len(files_changed)
            unit = "change" if meaningful_commits else "file"
            title = f"Krexion {suggested_version} — {change_count} {unit}{'s' if change_count != 1 else ''} updated"
        else:
            title = f"Krexion {suggested_version}"

        return {
            "needs_release": needs_release,
            "last_release_version": last_rel["version"] if last_rel else None,
            "last_release_date": last_rel["created_at"] if last_rel else None,
            "suggested_version": suggested_version,
            "suggested_title": title,
            "suggested_notes": notes,
            "suggested_severity": "recommended",
            "commit_count": len(commits),
            "meaningful_commit_count": len(meaningful_commits),
            "files_changed_count": len(files_changed),
            "notes_source": notes_source,  # "commits" | "files" | "none"
            "commits": commits[:50],
            "current_version": current_version(),
        }

    @router.post("/api/admin/releases/quick-publish")
    async def quick_publish(admin: dict = Depends(get_admin_dep)):
        """One-click publish — bundles auto-detect + create release.

        Behaviour:
          1. Run the same change-detection logic as `auto-detect`.
          2. Use the suggested version / title / notes when available.
          3. If no git history is available on this host (the typical
             VPS rsync deployment excludes the `.git` directory for
             security), gracefully fall back to bumping the patch
             component of the last published version and use a
             timestamped generic title + notes — so the admin still
             gets a single-click publish and customers get notified.
          4. Create the release with `published=true` immediately.

        Returns the inserted release document on success.
        """
        # Step 1 — change detection (same as auto-detect)
        last_rel = await _db.app_releases.find_one(
            {"published": True}, sort=[("created_at", -1)], projection={"_id": 0}
        )
        since_iso = last_rel["created_at"] if last_rel else None
        commits = _collect_commits_since(since_iso, limit=100)
        files_changed = _collect_changed_files_since(since_iso)

        base_ver = (last_rel["version"] if last_rel else current_version()) or "0.0.0"
        suggested_version = _bump_patch(base_ver)

        # Avoid collisions with any existing (draft or published) release
        existing = await _db.app_releases.find({}, {"_id": 0, "version": 1}).to_list(500)
        existing_versions = {r.get("version") for r in existing}
        while suggested_version in existing_versions:
            suggested_version = _bump_patch(suggested_version)

        meaningful_commits = [c for c in commits if not c.get("is_auto")]

        # Build title + notes — prefer real commit history, else fall
        # back to a file-summary, else fall back to a generic "hotfix"
        # message so quick-publish ALWAYS produces a usable release
        # (works on VPS hosts where .git is intentionally excluded
        # from the rsync deployment).
        if meaningful_commits:
            notes = "\n".join(f"- {c['subject']}" for c in meaningful_commits)
            change_count = len(meaningful_commits)
            unit = "change"
            title = f"v{suggested_version} — {change_count} {unit}{'s' if change_count != 1 else ''} updated"
        elif files_changed:
            bullets, _grp = _summarize_file_changes(files_changed)
            notes = "\n".join(bullets) if bullets else f"- Updated {len(files_changed)} file(s)"
            change_count = len(files_changed)
            title = f"v{suggested_version} — {change_count} file{'s' if change_count != 1 else ''} updated"
        else:
            # Generic fallback when no git history is available locally.
            # The release is still useful: it bumps the version, fires
            # the customer-side update banner, and triggers each
            # customer PC to pull the latest code from GitHub.
            notes = (
                "Latest updates, performance improvements, and bug fixes from "
                "the main branch. Install this update to pull the newest code "
                "and rebuild your local services."
            )
            title = f"v{suggested_version} — Update available"

        # Step 2 — create + publish immediately
        doc = {
            "id": str(uuid.uuid4()),
            "version": suggested_version,
            "title": title,
            "notes": notes,
            "severity": "recommended",
            "download_url": "",
            "min_required_version": "",
            "published": True,
            "created_at": _now_iso(),
            "created_by": admin.get("email") or admin.get("id"),
            "source": "quick-publish",
            "auto_detected": {
                "commit_count": len(commits),
                "meaningful_commit_count": len(meaningful_commits),
                "files_changed_count": len(files_changed),
                "used_fallback": not (meaningful_commits or files_changed),
            },
        }
        await _db.app_releases.insert_one(doc)
        doc.pop("_id", None)
        logger.info(
            f"[releases] quick-publish v{suggested_version} by "
            f"{doc['created_by']} (fallback={doc['auto_detected']['used_fallback']})"
        )
        return {
            "ok": True,
            "release": doc,
            "message": (
                f"Release v{suggested_version} published — all customers will "
                "be notified within 10 minutes."
            ),
        }

    @router.patch("/api/admin/releases/{rid}")
    async def patch_release(rid: str, body: dict, admin: dict = Depends(get_admin_dep)):
        allowed = {"title", "notes", "severity", "download_url", "published", "min_required_version"}
        upd = {k: v for k, v in body.items() if k in allowed}
        if not upd:
            raise HTTPException(400, "No editable fields supplied")
        upd["updated_at"] = _now_iso()
        r = await _db.app_releases.update_one({"id": rid}, {"$set": upd})
        if r.matched_count == 0:
            raise HTTPException(404, "Release not found")
        return {"updated": True}

    @router.delete("/api/admin/releases/{rid}")
    async def delete_release(rid: str, admin: dict = Depends(get_admin_dep)):
        r = await _db.app_releases.delete_one({"id": rid})
        if r.deleted_count == 0:
            raise HTTPException(404, "Release not found")
        return {"deleted": True}

    return router


def _build_customer_endpoints(get_user_dep):
    """Register customer-facing endpoints."""
    router = APIRouter(tags=["releases-customer"])

    @router.get("/api/system/version")
    async def get_version():
        """Public — returns the running version of this install."""
        return {
            "version": current_version(),
            "mode": (os.environ.get("KREXION_MODE") or "local").lower(),
        }

    @router.get("/api/system/latest-version")
    async def latest_version(x_krexion_license: Optional[str] = Header(None)):
        """License-authenticated — returns the latest published release plus
        whether the caller is behind."""
        await _validate_license(x_krexion_license)
        local = current_version()
        rel = await _db.app_releases.find_one(
            {"published": True}, sort=[("created_at", -1)], projection={"_id": 0}
        )
        if not rel:
            return {"current": local, "latest": None, "update_available": False}
        return {
            "current": local,
            "latest": rel,
            "update_available": is_newer(rel["version"], local),
        }

    @router.get("/api/system/public-latest")
    async def public_latest():
        """No-auth lite endpoint for the local dashboard banner so it can
        decide whether to nag the user — does not expose download URL."""
        rel = await _db.app_releases.find_one(
            {"published": True},
            sort=[("created_at", -1)],
            projection={"_id": 0, "version": 1, "title": 1, "severity": 1, "created_at": 1, "notes": 1},
        )
        local = current_version()
        if not rel:
            return {"current": local, "latest": None, "update_available": False}
        return {
            "current": local,
            "latest": rel,
            "update_available": is_newer(rel["version"], local),
        }

    @router.post("/api/system/install-update")
    async def trigger_update(request: Request, user: dict = Depends(get_user_dep)):
        """Customer clicks Update → flag is written so the host updater
        rebuilds containers.

        Three modes:
          - LOCAL install: writes flag directly (original behaviour)
          - CLOUD edge (krexion.com): bridges the call to the user's local
            PC via the bridge_module, so the customer never has to leave
            krexion.com or open localhost.
          - LOCAL receiving a bridge-relayed call: writes flag directly
            (recognised via X-Krexion-Bridge-Job header).
        """
        mode = (os.environ.get("KREXION_MODE") or "local").lower()
        is_bridge_relay = bool(request.headers.get("X-Krexion-Bridge-Job"))

        if mode != "local" and not is_bridge_relay:
            # We're on the cloud edge. Bridge the call to the user's local PC.
            try:
                from bridge_module import enqueue_bridge_job  # local import to avoid circular load
            except Exception:
                raise HTTPException(503, "Self-update bridge unavailable on this server")
            return await enqueue_bridge_job(
                user, "system/self-update", {},
                wait_for_result=True, wait_timeout=25,
            )

        if not user.get("is_admin"):
            raise HTTPException(403, "Only the admin user can trigger updates")
        try:
            UPDATE_FLAG_FILE.parent.mkdir(parents=True, exist_ok=True)
            payload = {
                "requested_at": _now_iso(),
                "requested_by": user.get("email") or user.get("id"),
                "current_version": current_version(),
                "via_bridge": is_bridge_relay,
            }
            UPDATE_FLAG_FILE.write_text(json.dumps(payload), encoding="utf-8")
            logger.info(f"[update] flag written: {UPDATE_FLAG_FILE} by {payload['requested_by']} bridge={is_bridge_relay}")
        except Exception as e:  # noqa: BLE001
            raise HTTPException(500, f"Could not write update flag: {e}")
        return {
            "ok": True,
            "flag_path": str(UPDATE_FLAG_FILE),
            "message": (
                "Update requested. The host updater will pull the new release "
                "and rebuild containers within 60 seconds. Krexion will be "
                "briefly unavailable during the swap."
            ),
        }

    return router
